version: "3"

services:
    web:
        build:
            context: ./
            dockerfile: ./devops/services/web/web.dev.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
            - "443:443"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: ./devops/services/app/app.dev.dockerfile
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
    adminer:
        image: dehy/adminer
        ports:
            - "6002:80"
    mysql:
        image: mysql:5.7
        environment:
            - "MYSQL_DATABASE=docker"
            - "MYSQL_ROOT_PASSWORD=secret"
        volumes:
            - mysql:/var/lib/mysql
    redis:
        image: redis:4.0
volumes:
    mysql:
